/**
 * Shared entry point for every /api route: verify the caller, build a Repo
 * scoped to them, run the handler, and turn anything thrown into JSON.
 */
import { env } from 'cloudflare:workers';
import { errorResponse, requireIdentity } from './access';
import { Repo } from './repo';

/**
 * `Env` comes from worker-configuration.d.ts, generated by `wrangler types`
 * from the bindings in wrangler.jsonc — so adding a binding there is a type
 * error here until it is handled.
 */
export async function withRepo(
  request: Request,
  run: (repo: Repo, email: string) => Promise<Response>,
): Promise<Response> {
  const bindings = env as Env & { ACCESS_DEV_BYPASS?: string };
  try {
    const who = await requireIdentity(request, bindings);
    const repo = new Repo(bindings.DB, bindings.DOCUMENTS, who);
    return await run(repo, who.email);
  } catch (error) {
    return errorResponse(error);
  }
}
